name: Deploy Backend to VPS

on:
  # Disabled - Using Coolify for deployment now
  # push:
  #   branches: [main]
  #   paths:
  #     - 'backend/**'
  #     - 'shared/**'
  #     - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to VPS
      run: |
        ssh -i ~/.ssh/id_ed25519 root@${{ secrets.VPS_HOST }} '
          cd /root/MatchTrex
          git fetch origin
          git reset --hard origin/main
          
          # Install/update dependencies
          source venv/bin/activate
          pip install -r requirements.txt
          
          # Restart services
          pkill -f "uvicorn.*mvp:app" || true
          pkill -f "python.*mvp.py" || true
          sleep 2
          
          # Start new instance
          nohup python mvp.py --server > webhook_logs.txt 2>&1 &
          
          echo "Backend deployed successfully"
        '
    
    - name: Verify deployment
      run: |
        sleep 10
        curl -f https://${{ secrets.VPS_HOST }}:9443/health || exit 1
        echo "✅ Backend is healthy"
    
    - name: Cleanup
      if: always()
      run: |
        rm -f ~/.ssh/id_ed25519